@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Dec 15 23:04:55 +0100 2019
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto bb3b4de853f0462ea87abd2c4a1ec801 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot napoje5_tb_behav xil_defaultlib.napoje5_tb -log elaborate.log"
call xelab  -wto bb3b4de853f0462ea87abd2c4a1ec801 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot napoje5_tb_behav xil_defaultlib.napoje5_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
